/** Optional React entry point for @handrail/ai-assistant. */
export {
  ConversationProvider,
  type ConversationFactoryProviderProps,
  type ConversationProviderFactory,
  type ConversationProviderProps,
  type ConversationReadableStore,
  type ConversationRuntimeProviderProps,
  type ConversationStoreProviderProps,
  type ConversationStoreRuntimeProviderProps,
} from "./context.js";
export {
  CopyMessageButton,
  conversationMessageText,
  type CopyMessageButtonProps,
  type MessageClipboard,
  type MessageCopyStatus,
} from "./message-actions.js";
export {
  useConversationLauncherBinding,
  useConversationReadState,
  useConversationActivitySnapshot,
  useConversationWorkspaceSnapshot,
  type ConversationLauncherBinding,
  type ConversationActivityReadable,
  type ConversationActivityRecord,
  type ConversationWorkspaceReadable,
} from "./workspace.js";
export {
  useConversationActions,
  useConversationSelector,
  useConversationSnapshot,
  useConversationStore,
  type ConversationActions,
} from "./hooks.js";
export {
  useSmartTranscriptFollow,
  type SmartTranscriptFollowOptions,
  type SmartTranscriptFollowResult,
} from "./transcript-follow.js";
export {
  createApplicationGatewayApprovalReviewAdapter,
  type ApplicationGatewayApprovalReviewAdapter,
} from "./application-gateway.js";
export {
  useConversationComposer,
  type ConversationComposerAttachment,
  type ConversationComposerAttachmentIntakeOptions,
  type ConversationComposerAttachmentStatus,
  type ConversationComposerDropProps,
  type ConversationComposerEnterBehavior,
  type ConversationComposerError,
  type ConversationComposerFileInputProps,
  type ConversationComposerImageIntakeOptions,
  type ConversationComposerResult,
  type ConversationComposerSubmission,
  type ConversationComposerTextareaProps,
  type UseConversationComposerOptions,
} from "./use-conversation-composer.js";
export {
  ChatDialogClose,
  ChatDialogContent,
  ChatDialogDescription,
  ChatDialogOverlay,
  ChatDialogPortal,
  ChatDialogRoot,
  ChatDialogTitle,
  ChatDialogTrigger,
  type ChatDialogCloseProps,
  type ChatDialogContentProps,
  type ChatDialogDescriptionProps,
  type ChatDialogOverlayProps,
  type ChatDialogPortalProps,
  type ChatDialogRootProps,
  type ChatDialogTitleProps,
  type ChatDialogTriggerProps,
} from "./dialog.js";
export {
  ChatDrawerClose,
  ChatDrawerContent,
  ChatDrawerDescription,
  ChatDrawerOverlay,
  ChatDrawerPortal,
  ChatDrawerRoot,
  ChatDrawerTitle,
  ChatDrawerTrigger,
  type ChatDrawerCloseProps,
  type ChatDrawerContentProps,
  type ChatDrawerDescriptionProps,
  type ChatDrawerOverlayProps,
  type ChatDrawerPortalProps,
  type ChatDrawerRootProps,
  type ChatDrawerSide,
  type ChatDrawerTitleProps,
  type ChatDrawerTriggerProps,
} from "./drawer.js";
export {
  ChatLauncherBadge,
  ChatLauncherClose,
  ChatLauncherDescription,
  ChatLauncherPanel,
  ChatLauncherPortal,
  ChatLauncherRoot,
  ChatLauncherStatus,
  ChatLauncherTitle,
  ChatLauncherTrigger,
  type ChatLauncherBadgeProps,
  type ChatLauncherCloseProps,
  type ChatLauncherConnectionStatus,
  type ChatLauncherDescriptionProps,
  type ChatLauncherPanelProps,
  type ChatLauncherPortalProps,
  type ChatLauncherRootProps,
  type ChatLauncherState,
  type ChatLauncherStatusProps,
  type ChatLauncherTitleProps,
  type ChatLauncherTriggerProps,
  type ChatLauncherTurnStatus,
} from "./launcher.js";
export {
  ChatTabsContent,
  ChatTabsList,
  ChatTabsRoot,
  ChatTabsTrigger,
  type ChatTabsActivationMode,
  type ChatTabsContentProps,
  type ChatTabsListProps,
  type ChatTabsOrientation,
  type ChatTabsRootProps,
  type ChatTabsTriggerProps,
} from "./tabs.js";
export {
  CitationItem,
  CitationList,
  type CitationItemNativeProps,
  type CitationItemProps,
  type CitationListProps,
  type CitationLocatorActivateHandler,
  type CitationLocatorRenderer,
  type CitationRenderer,
} from "./citations.js";
export {
  ConversationPickerArchive,
  ConversationPickerClear,
  ConversationPickerCreateForm,
  ConversationPickerEmpty,
  ConversationPickerErrorMessage,
  ConversationPickerItem,
  ConversationPickerList,
  ConversationPickerLoading,
  ConversationPickerLoadMore,
  ConversationPickerPermanentDelete,
  ConversationPickerRenameForm,
  ConversationPickerRestore,
  ConversationPickerRoot,
  ConversationPickerSelect,
  useConversationPicker,
  type ConversationPickerActionProps,
  type ConversationPickerArchiveProps,
  type ConversationPickerClearProps,
  type ConversationPickerConfirmation,
  type ConversationPickerConfirmationRequest,
  type ConversationPickerController,
  type ConversationPickerCreateFormProps,
  type ConversationPickerCreateInput,
  type ConversationPickerError,
  type ConversationPickerErrorCode,
  type ConversationPickerIdempotencyKeyFactory,
  type ConversationPickerIdempotencyRequest,
  type ConversationPickerItemProps,
  type ConversationPickerItemNativeProps,
  type ConversationPickerItemRenderer,
  type ConversationPickerListNativeProps,
  type ConversationPickerListProps,
  type ConversationPickerLoadMoreProps,
  type ConversationPickerMutationInput,
  type ConversationPickerOpenHandler,
  type ConversationPickerOpenInput,
  type ConversationPickerOperation,
  type ConversationPickerOperationState,
  type ConversationPickerPermanentDeleteProps,
  type ConversationPickerRenameFormProps,
  type ConversationPickerRenameInput,
  type ConversationPickerRestoreProps,
  type ConversationPickerRootProps,
  type ConversationPickerRuntimeRegistry,
  type ConversationPickerSelectProps,
  type UseConversationPickerOptions,
} from "./conversation-picker.js";
export {
  ApprovalReviewConfirm,
  ApprovalReviewEmpty,
  ApprovalReviewErrorMessage,
  ApprovalReviewGroup,
  ApprovalReviewItem,
  ApprovalReviewList,
  ApprovalReviewLoading,
  ApprovalReviewReject,
  ApprovalReviewRoot,
  ApprovalReviewStatus,
  useApprovalReview,
  type ApprovalReviewActionProps,
  type ApprovalReviewConfirmProps,
  type ApprovalReviewConditionalProps,
  type ApprovalReviewController,
  type ApprovalReviewDecisionCode,
  type ApprovalReviewDecisionHandler,
  type ApprovalReviewTransitionHandler,
  type ApprovalReviewDecisionIdentity,
  type ApprovalReviewDecisionIdentityFactory,
  type ApprovalReviewDecisionIdentityRequest,
  type ApprovalReviewDecisionState,
  type ApprovalReviewGroupModel,
  type ApprovalReviewGroupNativeProps,
  type ApprovalReviewGroupProps,
  type ApprovalReviewGroupRenderer,
  type ApprovalReviewItemNativeProps,
  type ApprovalReviewItemProps,
  type ApprovalReviewItemRenderer,
  type ApprovalReviewListNativeProps,
  type ApprovalReviewListProps,
  type ApprovalReviewLoadError,
  type ApprovalReviewLoadInput,
  type ApprovalReviewProposalLoader,
  type ApprovalReviewProposalSubscription,
  type ApprovalReviewRejectProps,
  type ApprovalReviewRootNativeProps,
  type ApprovalReviewRootProps,
  type ApprovalReviewStatusNativeProps,
  type ApprovalReviewStatusProps,
  type ApprovalReviewSubscriptionInput,
  type UseApprovalReviewOptions,
} from "./approval-review.js";
export {
  TranscriptionControlsCancel,
  TranscriptionControlsRetry,
  TranscriptionControlsRoot,
  TranscriptionControlsStart,
  TranscriptionControlsStatus,
  TranscriptionControlsStop,
  useTranscriptionControls,
  useCapturedAudioTranscription,
  type CapturedAudioTranscriptionInput,
  type UseCapturedAudioTranscriptionOptions,
  type TranscriptionCaptureFactory,
  type TranscriptionCaptureFactoryInput,
  type TranscriptionControlsActionProps,
  type TranscriptionControlsCancelProps,
  type TranscriptionControlsController,
  type TranscriptionControlsError,
  type TranscriptionControlsErrorStage,
  type TranscriptionControlsRetryProps,
  type TranscriptionControlsRootNativeProps,
  type TranscriptionControlsRootProps,
  type TranscriptionControlsStartProps,
  type TranscriptionControlsStatus as TranscriptionControlsLifecycleStatus,
  type TranscriptionControlsStatusNativeProps,
  type TranscriptionControlsStatusProps,
  type TranscriptionControlsStopProps,
  type TranscriptionInvoker,
  type TranscriptionRequestIdentity,
  type TranscriptionRequestIdentityFactory,
  type TranscriptionRequestIdentityInput,
  type TranscriptionUpload,
  type TranscriptionUploadInput,
  type UseTranscriptionControlsOptions,
} from "./transcription.js";
export {
  RealtimeVoiceCancel,
  RealtimeVoiceCapabilities,
  RealtimeVoiceControlsContext,
  RealtimeVoiceControlsRoot,
  RealtimeVoiceControlsStatus,
  RealtimeVoiceEndSession,
  RealtimeVoiceInterrupt,
  RealtimeVoiceMute,
  RealtimeVoiceStart,
  RealtimeVoiceStopMicrophone,
  RealtimeVoiceUnmute,
  useRealtimeVoiceControls,
  useRealtimeVoiceControlsContext,
  type ExternalRealtimeVoiceControlsOptions,
  type OwnedRealtimeVoiceControlsOptions,
  type RealtimeVoiceActionProps,
  type RealtimeVoiceCancelProps,
  type RealtimeVoiceCapabilitiesNativeProps,
  type RealtimeVoiceCapabilitiesProps,
  type RealtimeVoiceCapabilityModel,
  type RealtimeVoiceCapabilityName,
  type RealtimeVoiceControllerFactory,
  type RealtimeVoiceControlsContextValue,
  type RealtimeVoiceControlsController,
  type RealtimeVoiceControlsRootNativeProps,
  type RealtimeVoiceControlsRootProps,
  type RealtimeVoiceControlsStatusNativeProps,
  type RealtimeVoiceControlsStatusProps,
  type RealtimeVoiceEndSessionProps,
  type RealtimeVoiceInterruptProps,
  type RealtimeVoiceMuteProps,
  type RealtimeVoiceStartProps,
  type RealtimeVoiceStopMicrophoneProps,
  type RealtimeVoiceUnmuteProps,
  type UseRealtimeVoiceControlsOptions,
} from "./realtime-voice.js";
export * from "./primitives.js";
export { ToolActivity, type ToolActivityProps } from "./tool-activity.js";

export { useConversationApprovals, type ConversationApprovalResources } from "./use-conversation-approvals.js";

export { useRealtimeWorkspaceActivity } from "./realtime-workspace.js";
